name: nostressr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_core: ^4.1.0
  firebase_storage: ^13.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/Stress_Buster__3_-removebg-preview.png